export const config: WebdriverIO.Config = {
    runner: "local",
    tsConfigPath: "./tsconfig.json",
    specs: ["./tests/features/**/*.feature"],
    suites: {
      login: ["./tests/features/login.feature"],
      checkboxes: [".tests/features/checkboxes.feature"],
      dropdown: [".tests/features/dropdown.feature"],
      fileUpload: [".tests/features/file-upload.feature"],
    },
    exclude: [],
    maxInstances: 1,
    capabilities: [
      {
        browserName: "chrome",
      },
    ],
    logLevel: "info",
    bail: 0,
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    framework: "cucumber",
    reporters: ["spec", ["allure", { outputDir: "allure-results" }]],
    cucumberOpts: {
      require: ["./tests/step-definitions/*.ts"],
      backtrace: false,
      requireModule: [],
      dryRun: false,
      failFast: false,
      name: [],
      snippets: true,
      source: true,
      strict: false,
      tagExpression: "",
      timeout: 60000,
      ignoreUndefinedDefinitions: false,
    },
    baseUrl: "http://localhost:8080",
  };